# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Ecological Modeling (BI382), Colby College
tagline:          'A Jekyll theme'
description:      ''
url:              http://ecologistchris.github.io
baseurl:          /

author:
  name:           'Chris Moore'
  url:            https://mutualismecology.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
