# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
plugins: [jekyll-paginate, jekyll-gist]

# Setup
title:            Ecological Modeling @ Colby College
tagline:          'A Jekyll theme'
description:      'A course on mathematical, computational, and statistical ecology--'
url:              http://ecologistchris.github.io
baseurl:          /

author:
  name:           'Chris Moore'
  url:            https://mutualismecology.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
